### ISSUE TITLE
Disabled Color

### ISSUE THREAD

**Issue by fernandodeveloper** [DreaminginCodeZH/MaterialEditText#2]
Its possible do change color in disabled mode?

**Comment by zhanghai** [comment]
The color when disabled is `?android:textColorHint`, with alpha multiplied by `?android:disabledAlpha`, and this gives the color just as the framework drawable. See the [source](https://github.com/DreaminginCodeZH/MaterialEditText/blob/master/library/src/main/java/me/zhanghai/android/materialedittext/MaterialEditTextBackgroundDrawable.java#L475).

If you really want to modify such color, a possible workaround without building a custom version of this library, is to create a new theme which extends your application theme, then modify `android:textColorHint` and `android:disabledAlpha`, and finally set it on the `MaterialEditText` widget with `android:theme`.
